#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

TAG=${TAG:-${VERSION_TAG}${SUFFIX}}
IMAGE_NAME=${IMAGE_NAME:-kine}
IMAGE=${REPO}/${IMAGE_NAME}:${TAG}

echo "FROM ${IMAGE}" | docker build --label org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}" -t "${IMAGE}" -

docker push ${IMAGE}
echo Pushed ${IMAGE}
