name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      REPO: ghcr.io/${{ github.repository_owner }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.8'
    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0
    - name: Login to GitHub Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: ./scripts/build
    - run: ./scripts/test
    - run: ./scripts/validate
    - run: ./scripts/validate-ci
    - run: ./scripts/package
    - run: ./scripts/distribute
